# Generated by Django 5.0.4 on 2024-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=64)),
                ('map_name', models.CharField(max_length=64)),
                ('server_password_hash', models.CharField(max_length=128)),
            ],
        ),
    ]
