# Generated by Django 5.0.4 on 2024-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='server_name',
            new_name='server_session_name',
        ),
        migrations.AddField(
            model_name='server',
            name='admin_password_hash',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='admin_password_salt',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='max_server_players',
            field=models.IntegerField(default=70, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='server_password_salt',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_password_hash',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
